import 'dart:io';

const _header = '''// GENERATED FILE - DO NOT EDIT.
// Generated by tool/generate_tessellation_tables.dart
''';

List<int> _alphaLut(int sampleCount) {
  final lut = <int>[];
  for (int i = 0; i <= sampleCount; i++) {
    lut.add(((i * 255 + (sampleCount >> 1)) ~/ sampleCount).clamp(0, 255));
  }
  return lut;
}

void main() {
  final lut4 = _alphaLut(4);
  final lut16 = _alphaLut(16);

  final buffer = StringBuffer();
  buffer.writeln(_header);
  buffer.writeln('const List<int> kTessellationAlphaLut4 = <int>[');
  buffer.writeln('  ${lut4.join(', ')},');
  buffer.writeln('];');
  buffer.writeln('');
  buffer.writeln('const List<int> kTessellationAlphaLut16 = <int>[');
  buffer.writeln('  ${lut16.join(', ')},');
  buffer.writeln('];');

  File('lib/src/rasterization_algorithms/tessellation/tessellation_tables.dart')
      .writeAsStringSync(buffer.toString());
}
