// GENERATED FILE - DO NOT EDIT.
// Generated by tool/generate_tessellation_tables.dart

const List<int> kTessellationAlphaLut4 = <int>[
  0, 64, 128, 191, 255,
];

const List<int> kTessellationAlphaLut16 = <int>[
  0, 16, 32, 48, 64, 80, 96, 112, 128, 143, 159, 175, 191, 207, 223, 239, 255,
];
